### ISSUE TITLE
Readme suggestion - module autoloading

### ISSUE THREAD

**Issue by philBrown** [beberlei/zf-doctrine#4]
You don't need to loop over each module name and add autoloaders if you use the "modules" resource plugin. See http://framework.zend.com/manual/en/zend.application.available-resources.html#zend.application.available-resources.modules

**Comment by beberlei** [comment]
really? The modules resource plugin does no autoloading from what i can see in the code.

**Comment by philBrown** [comment]
Just going by the documentation.

> Zend_Application_Resource_Modules is used to initialize your application modules. If your module has a Bootstrap.php file in its root, and it contains a class named Module_Bootstrap (where "Module" is the module name), then it will use that class to bootstrap the module.
> By default, an instance of Zend_Application_Module_Autoloader will be created for the module, using the module name and directory to initialize it.

**Comment by philBrown** [comment]
Oops, didn't mean to close the issue.

The code appears to be in Zend_Application_Bootstrap_Bootstrap::getResourceLoader() which is called as part of the Bootstrap constructor.

**Comment by beberlei** [comment]
I'll look into it and see if i can optimize this section. I find the Zend application code hard to understand ;-)
