### ISSUE TITLE
View Helper uses short open tags

### ISSUE THREAD

**Issue by fcrespel** [beberlei/zf-doctrine#7]
The file `library/ZFDoctrine/View/Helper/files/scripts/list.phtml` (commited in beberlei/zf-doctrine@5a0abb4ad6f1a057dc018e7658e64652e7dd1e80) uses short open tags, which are disabled by default in most PHP installations. Please consider replacing all `<?=` by `<?php echo` for maximum compatibility.

**Comment by beberlei** [comment]
fixed
